/// The Android build configuration `upkeep` was able to read.
///
/// Every field is nullable on purpose. Flutter projects have been generated by
/// six years of templates, Groovy and Kotlin DSL, plugins block and legacy
/// buildscript. Reporting "not found" is always better than reporting a guess.
class AndroidConfig {
  const AndroidConfig({
    this.gradleVersion,
    this.agpVersion,
    this.kotlinVersion,
    this.compileSdk,
    this.compileSdkIsFlutterManaged = false,
    this.jdkVersion,
    this.jdkSource,
    this.jdkUnavailableReason,
    this.wrapperPinsChecksum = false,
    this.notes = const [],
  });

  /// Gradle wrapper version, from `gradle-wrapper.properties`.
  final String? gradleVersion;

  /// Android Gradle Plugin version.
  final String? agpVersion;

  /// Kotlin Gradle plugin version.
  final String? kotlinVersion;

  /// The project's `compileSdk`, when written as a literal.
  final int? compileSdk;

  /// True when `compileSdk` defers to `flutter.compileSdkVersion`.
  final bool compileSdkIsFlutterManaged;

  /// Local JDK major version, when detectable.
  final int? jdkVersion;

  /// How the JDK version was found, for honest reporting.
  final String? jdkSource;

  /// Why no JDK version is known, when [jdkVersion] is null.
  final String? jdkUnavailableReason;

  /// True when the wrapper pins a `distributionSha256Sum`, which ties it to one
  /// exact distribution and makes editing the URL alone unsafe.
  final bool wrapperPinsChecksum;

  /// Files that were looked at but could not be read.
  final List<String> notes;

  /// True when an `android/` directory exists at all.
  bool get hasAndroid => gradleVersion != null || agpVersion != null || compileSdk != null;

  /// Paths, relative to the project root, that [fromFiles] reads.
  static const files = [
    'android/gradle/wrapper/gradle-wrapper.properties',
    'android/settings.gradle.kts',
    'android/settings.gradle',
    'android/build.gradle.kts',
    'android/build.gradle',
    'android/app/build.gradle.kts',
    'android/app/build.gradle',
  ];

  /// Builds the configuration from file contents keyed by the paths in [files].
  ///
  /// Missing keys are files that do not exist. Keeping this free of any file
  /// system is what lets the same reading run in a browser.
  static AndroidConfig fromFiles(
    Map<String, String> contents, {
    int? jdkVersion,
    String? jdkSource,
    String? jdkUnavailableReason,
  }) {
    final notes = <String>[];
    final wrapper = contents['android/gradle/wrapper/gradle-wrapper.properties'];
    if (wrapper == null) notes.add('missing gradle-wrapper.properties');

    return AndroidConfig(
      gradleVersion: wrapper == null
          ? null
          : RegExp(r'gradle-([0-9]+(?:\.[0-9]+)*)-(?:all|bin)\.zip').firstMatch(wrapper)?.group(1),
      agpVersion: _pluginVersion(
        contents,
        pluginId: 'com.android.application',
        legacyClasspath:
            RegExp(r'''com\.android\.tools\.build:gradle:([0-9]+\.[0-9]+(?:\.[0-9]+)?)'''),
      ),
      kotlinVersion: _pluginVersion(
        contents,
        pluginId: 'org.jetbrains.kotlin.android',
        legacyClasspath: RegExp(r'''kotlin_version\s*=\s*['"]([0-9]+\.[0-9]+(?:\.[0-9]+)?)['"]'''),
      ),
      compileSdk: _compileSdk(contents),
      compileSdkIsFlutterManaged: _appGradle(contents).any((t) => t.contains('flutter.compileSdkVersion')),
      jdkVersion: jdkVersion,
      jdkSource: jdkSource,
      jdkUnavailableReason: jdkUnavailableReason,
      wrapperPinsChecksum: wrapper?.contains('distributionSha256Sum') ?? false,
      notes: notes,
    );
  }

  /// Finds a plugin version from the `plugins { }` block, falling back to the
  /// legacy `buildscript` form that Flutter templates used before 2023.
  static String? _pluginVersion(
    Map<String, String> contents, {
    required String pluginId,
    required RegExp legacyClasspath,
  }) {
    final modern = RegExp(
      '''id\\s*[("']+${RegExp.escape(pluginId)}["')]+\\s*(?:version)?\\s*["']([0-9]+\\.[0-9]+(?:\\.[0-9]+)?)["']''',
    );
    for (final name in const [
      'android/settings.gradle.kts',
      'android/settings.gradle',
      'android/build.gradle.kts',
      'android/build.gradle',
    ]) {
      final text = contents[name];
      if (text == null) continue;
      final hit = modern.firstMatch(text) ?? legacyClasspath.firstMatch(text);
      if (hit != null) return hit.group(1);
    }
    return null;
  }

  static Iterable<String> _appGradle(Map<String, String> contents) => [
        for (final name in const ['android/app/build.gradle.kts', 'android/app/build.gradle'])
          if (contents[name] != null) contents[name]!,
      ];

  static int? _compileSdk(Map<String, String> contents) {
    for (final text in _appGradle(contents)) {
      final hit = RegExp(r'compileSdk(?:Version)?\s*=?\s*([0-9]{2})\b').firstMatch(text);
      if (hit != null) return int.tryParse(hit.group(1)!);
    }
    return null;
  }
}
