import 'dart:io';

import 'package:path/path.dart' as p;

/// The Android build configuration `upkeep` was able to read off disk.
///
/// Every field is nullable on purpose. Flutter projects have been generated by
/// six years of templates, Groovy and Kotlin DSL, plugins block and legacy
/// buildscript. Reporting "not found" is always better than reporting a guess.
class AndroidConfig {
  const AndroidConfig({
    this.gradleVersion,
    this.agpVersion,
    this.kotlinVersion,
    this.compileSdk,
    this.compileSdkIsFlutterManaged = false,
    this.jdkVersion,
    this.jdkSource,
    this.notes = const [],
  });

  /// Gradle wrapper version, from `gradle-wrapper.properties`.
  final String? gradleVersion;

  /// Android Gradle Plugin version.
  final String? agpVersion;

  /// Kotlin Gradle plugin version.
  final String? kotlinVersion;

  /// The project's `compileSdk`, when written as a literal.
  final int? compileSdk;

  /// True when `compileSdk` defers to `flutter.compileSdkVersion`.
  final bool compileSdkIsFlutterManaged;

  /// Local JDK major version, when detectable.
  final int? jdkVersion;

  /// How the JDK version was found, for honest reporting.
  final String? jdkSource;

  /// Files that were looked at but could not be read.
  final List<String> notes;

  /// True when an `android/` directory exists at all.
  bool get hasAndroid => gradleVersion != null || agpVersion != null || compileSdk != null;

  /// Reads whatever Android build configuration exists under [projectRoot].
  ///
  /// Returns null when there is no `android/` directory, which is normal for
  /// pure Dart packages and for Flutter projects targeting other platforms.
  static AndroidConfig? load(String projectRoot) {
    final androidDir = Directory(p.join(projectRoot, 'android'));
    if (!androidDir.existsSync()) return null;

    final notes = <String>[];
    final jdk = _localJdk();

    return AndroidConfig(
      gradleVersion: _gradleWrapperVersion(androidDir, notes),
      agpVersion: _pluginVersion(
        androidDir,
        notes,
        pluginId: 'com.android.application',
        legacyClasspath:
            RegExp(r'''com\.android\.tools\.build:gradle:([0-9]+\.[0-9]+(?:\.[0-9]+)?)'''),
      ),
      kotlinVersion: _pluginVersion(
        androidDir,
        notes,
        pluginId: 'org.jetbrains.kotlin.android',
        legacyClasspath: RegExp(r'''kotlin_version\s*=\s*['"]([0-9]+\.[0-9]+(?:\.[0-9]+)?)['"]'''),
      ),
      compileSdk: _compileSdk(androidDir, notes),
      compileSdkIsFlutterManaged: _compileSdkIsFlutterManaged(androidDir),
      jdkVersion: jdk?.$1,
      jdkSource: jdk?.$2,
      notes: notes,
    );
  }

  static String? _gradleWrapperVersion(Directory android, List<String> notes) {
    final file = File(p.join(android.path, 'gradle', 'wrapper', 'gradle-wrapper.properties'));
    final text = _read(file, notes);
    if (text == null) return null;
    final match = RegExp(r'gradle-([0-9]+(?:\.[0-9]+)*)-(?:all|bin)\.zip').firstMatch(text);
    return match?.group(1);
  }

  /// Finds a plugin version from the `plugins { }` block, falling back to the
  /// legacy `buildscript` form that Flutter templates used before 2023.
  static String? _pluginVersion(
    Directory android,
    List<String> notes, {
    required String pluginId,
    required RegExp legacyClasspath,
  }) {
    final modern = RegExp(
      '''id\\s*[("']+${RegExp.escape(pluginId)}["')]+\\s*(?:version)?\\s*["']([0-9]+\\.[0-9]+(?:\\.[0-9]+)?)["']''',
    );

    for (final name in const [
      'settings.gradle.kts',
      'settings.gradle',
      'build.gradle.kts',
      'build.gradle'
    ]) {
      final text = _read(File(p.join(android.path, name)), notes, required: false);
      if (text == null) continue;
      final hit = modern.firstMatch(text) ?? legacyClasspath.firstMatch(text);
      if (hit != null) return hit.group(1);
    }
    return null;
  }

  static int? _compileSdk(Directory android, List<String> notes) {
    for (final name in const ['build.gradle.kts', 'build.gradle']) {
      final text = _read(File(p.join(android.path, 'app', name)), notes, required: false);
      if (text == null) continue;
      final hit = RegExp(r'compileSdk(?:Version)?\s*=?\s*([0-9]{2})\b').firstMatch(text);
      if (hit != null) return int.tryParse(hit.group(1)!);
    }
    return null;
  }

  static bool _compileSdkIsFlutterManaged(Directory android) {
    for (final name in const ['build.gradle.kts', 'build.gradle']) {
      final file = File(p.join(android.path, 'app', name));
      if (!file.existsSync()) continue;
      if (file.readAsStringSync().contains('flutter.compileSdkVersion')) return true;
    }
    return false;
  }

  /// The local JDK, as reported by `java -version`.
  ///
  /// This is the JDK on PATH, which is not necessarily the one Gradle uses.
  /// The report says so rather than pretending otherwise.
  static (int, String)? _localJdk() {
    try {
      final result = Process.runSync('java', ['-version']);
      final output = '${result.stdout}${result.stderr}';
      final hit = RegExp(r'version\s+"([0-9]+)(?:\.([0-9]+))?').firstMatch(output);
      if (hit == null) return null;
      final major = int.parse(hit.group(1)!);
      // Java 8 and earlier report as 1.8.x; the real major is the second part.
      if (major == 1 && hit.group(2) != null) {
        return (int.parse(hit.group(2)!), 'java -version on PATH');
      }
      return (major, 'java -version on PATH');
    } on ProcessException {
      return null;
    }
  }

  static String? _read(File file, List<String> notes, {bool required = true}) {
    if (!file.existsSync()) {
      if (required) notes.add('missing ${p.basename(file.path)}');
      return null;
    }
    try {
      return file.readAsStringSync();
    } on FileSystemException {
      notes.add('could not read ${p.basename(file.path)}');
      return null;
    }
  }
}
